### ISSUE TITLE
固定ジャンル追加検索処理

### ISSUE THREAD

**Issue by nozutaku** [hiroaki-ohkawa/ikoma-library-app-proto#11]
検索画面の固定ジャンルを選択された場合に、 ( #9 ) 
ジャンルの本を抽出　＋　図書館情報取得　＋司書情報取得　→ソート

**Comment by nozutaku** [comment]
検索に対応しました。16c9adb06951404a9e7761773bc16de41a5ec3fc

＜入力＞
SelectBooks.searchkeyword に文字列を入れてget_list呼ぶ

- 文字列をそのまま入れると曖昧検索（現時点では楽天のタイトルに入れて検索するだけ。連想検索webcatplusのAPIが無いことが判明。。。）
- 楽天にそのまま渡せる下記形式を渡すとそのまま楽天ブックス検索します

例："title=いないいないばあ&author=吉岡靖晃&publisherName=講談社"

※APIの中でurlencodingを行うのでそのままの文字列を渡してもらってOKです


＜出力＞
- おすすめ検索と同様に「図書館情報有無」や「司書おすすめ有無」を検索してbooklistを返します

※注意！！！
booklistの件数が３０件固定では無くなりました。０件や１件の場合もあります。arrayからspliceで件数を減らしています。

**Comment by nozutaku** [comment]
大川さん、まだ野津が用意した方に切り替えてないように見えます。対応お願いします～

**Comment by hiroaki-ohkawa** [comment]
キーワード検索の呼び出し方が分かりませんでした。
WebAPIにクエリパラメータを渡す必要があると思います。

**Comment by nozutaku** [comment]
> キーワード検索の呼び出し方が分かりませんでした。

このgithub issueの３つ上に記載していますが、
SelectBooks.searchkeyword に文字列（「どうぶつ」など）を入れてget_list呼ぶようお願いします。

大きく入力のためのグローバル変数（構造体）が下記２つあります。

- SelectBooks 同じセッション内固有の指定入力。ページ番号やキーワード検索など
https://github.com/hiroaki-ohkawa/ikoma-library-app-proto/blob/integrate-recommendation-2/routes/api/recommendation/get_list.js#L200

- Setting　年齢など固定のデータ指定。
https://github.com/hiroaki-ohkawa/ikoma-library-app-proto/blob/integrate-recommendation-2/routes/api/recommendation/get_list.js#L91

**Comment by nozutaku** [comment]
#51 同件ですのでcloseします。　#16 待ち状況。
