### ISSUE TITLE
表示形式の設定がカルーセルの場合、検索結果の表示がおかしい

### ISSUE THREAD

**Issue by hiroaki-ohkawa** [hiroaki-ohkawa/ikoma-library-app-proto#13]
現在のmasterで発生。
原因と、いつからこうなっているのかは不明。
要調査。
優先度は低め。

**Comment by hiroaki-ohkawa** [comment]
どうもslickブランチのどこかのコミットから楽天API呼び出し時にエラーが発生するようになっているようです。
おすすめONだとエラーになりませんが、おすすめOFFだとエラーになります。
コミット19c3240ではエラーにならないことを確認しました。
コミット11aa0edではエラーになります。

**Comment by acliss19xx** [comment]
コミットID dd7a7f4c で修正済み。
