### ISSUE TITLE
市内学校おすすめ本

### ISSUE THREAD

**Issue by nozutaku** [hiroaki-ohkawa/ikoma-library-app-proto#17]
【概要】
市内の幼稚園/保育園/小学校/中学校　のおススメ本を司書おすすめと同様に子供に提示する

【目的】
- 子供に学校おススメの本に興味をもってもらう。他の本と違い、自分の学校がおススメしているとなれば多少は興味持つはず。
- 将来自分が行く予定の学校がおススメしている本にも興味を持つ可能性有
- 学校側としては良本をお薦めすることで市民にアピールして将来その学校に来たい！と思わせることができる（ブランドイメージ向上）
- このアプリを市のみんなで作って、育ててる感　醸成
- （おまけ）コンテスト系は足を使って作ったデータ、いろんな人を巻き込んで作ったデータは評価ポイント高い

【仕様】
- 一覧画面→　司書おススメと同様のふくろうアイコン表示。司書や学校のおすすめが１つでもあればフクロウアイコン表示する。１つも無ければ非表示
- 詳細画面→　学校名表示。校章画像or専用アイコンかは未定（権利の関係もあるのでとりあえずは専用新規アイコンでしょうね）

**Comment by nozutaku** [comment]
市内学校お薦め対応を integrate-recommendation branchへコミットしました。
heroku でcsvをどう配置して読み込むか分からなかったので今回はソース内部にテーブルを持ってます。
呼び出し側での実装は可能かと思いますので実装開始お願いします。
(csv対応もぼちぼち行います）

I/Fは　get_list()の戻りのbooklistに学校お薦めの場合にはCitySchoolRecommended　というarrayに学校番号が入ります。
(I/F変更は可能ですのでいつでも連絡ください。学校番号にするかそれを表す定数にするか悩みましたが番号にしました。他のI/Fも定数を入れるのは不自然かと思い出してきたので別途相談します）

I/F仕様書にも追記しています。
https://drive.google.com/drive/u/0/folders/0BxslmPmJBoYIU1hjaHZMdkM0cDg

**Comment by nozutaku** [comment]
"School_recomm" というbranchを作成してcommitしました。
ただし、データベースが無い時は異常終了する不具合があります。修正すべきですがわかりませんでしたので後回し。

**(手順)**
下記のSchool_recom_DB.csvをpostgresへimportする。googledrive→doc→学校お薦めリスト→release
https://drive.google.com/drive/u/0/folders/0BxslmPmJBoYIa29kSEN5SmNCNnM

**(csvをpostgresへimportする手順詳細)**  #21 参照


PGadmin4アプリ起動
→ツリービューで"PostgreSQL"の下を開き、"Databases"を右クリック "Create→Database"を選択すると、ダイアログが出る。
Databaseには"naniyomodb"と入力
→"Save"を押すと、DBが作られる。


①postgres の「SQL shell(psql)」起動
２つ目のdatabasesのところで"naniyomoDB"を入力

②テーブル作成
CREATE TABLE school_recom_DB (
title varchar(128),
isbn10 varchar(16),
school varchar(64),
age varchar(16)
);

③csv import
COPY school_recom_DB FROM 'C:\work\School_recom_DB.csv' WITH CSV;

以上　

●確認
SELECT * FROM school_recom_DB;

●削除
DROP table school_recom_DB;
\d			//テーブル削除確認

**Comment by hiroaki-ohkawa** [comment]
csvファイルはcommitされてないようですが、どうやって作ればよいですか？

**Comment by nozutaku** [comment]
2つ目のダミー保育園を準備しました。csvファイルは下記。

https://drive.google.com/drive/u/0/folders/0BxslmPmJBoYIa29kSEN5SmNCNnM
