### ISSUE TITLE
main.jsのリファクタリング

### ISSUE THREAD

**Issue by hiroaki-ohkawa** [hiroaki-ohkawa/ikoma-library-app-proto#18]
重複コードが多くなったり、１関数の行数が多くなってきており、見通しが悪い。
早めにリファクタリングしないと不具合の原因になる。

**Comment by acliss19xx** [comment]
行数が多くなっているの原因の一つに、ｊｓ内に書いてあるhtmlタグがあります。jsテンプレートなどを導入して、htmlタグ関係は外部ファイルにするとすっきりすると思います。

**Comment by acliss19xx** [comment]
JSテンプレートエンジンだと、サーバーサイドでejsを使用しているので、handlebar.js jsrender.jsがいいかと思います。
handlebar.js  http://handlebarsjs.com/
jsRender  https://www.jsviews.com/
