### ISSUE TITLE
おすすめON、OFFでのjsonデータ取得時のプロパティー名をそろえる

### ISSUE THREAD

**Issue by acliss19xx** [hiroaki-ohkawa/ikoma-library-app-proto#19]
現行
おすすめONの場合 MidiumImageURL  Title  Author  Isbn
おすすめOFFの場合 mediumImageUrl　　title　　author　　isbn 

大文字小文字もそろえて、viewの使いまわしをするため

**Comment by nozutaku** [comment]
本件、10/16のMTGの時に話しましたが非対応予定です。

おすすめONでもOFFでも野津の用意したAPIを呼んでbooklistを取得する方向です。

https://docs.google.com/document/d/18YtNxrxSriSWDJjaIIi5r74JDw45t2JnA-fx8XbS42g/edit

残件無いと思ってますのでcloseで良いでしょうか？　＞猪上さん

**Comment by hiroaki-ohkawa** [comment]
一本化した後でcloseしたらいいんじゃないですかね。
