### ISSUE TITLE
一覧表示されない

### ISSUE THREAD

**Issue by acliss19xx** [hiroaki-ohkawa/ikoma-library-app-proto#20]
条件:オススメON、タイル

上記条件でなによもアイコン押下後、表示される一覧から1冊選び、
詳細表示のまま、なによもアイコン押下すると画面に何も表示されなくなります。
gotoSearch() 関数でresultを表示にしていないのが原因

**Comment by nozutaku** [comment]
対応済かと思いますのでcloseお願いします～
