### ISSUE TITLE
図書館貸出有無の実装

### ISSUE THREAD

**Issue by nozutaku** [hiroaki-ohkawa/ikoma-library-app-proto#4]
●一覧画面
- 登録図書館ですぐに借りれる場合はアイコン表示（図書館の名前が入ってないアイコン。複数図書館を１つのアイコンで表現）
- 登録図書館ですぐに借りれない場合はグレーアウトアイコン表示
- 生駒市図書館に無い場合はアイコン非表示

●詳細画面
-登録図書館ですぐに借りれる場合はアイコン表示（図書館の名前表示。複数図書館登録ある場合は複数アイコン表示）
- 登録図書館ですぐに借りれない場合はグレーアウトアイコン表示
- 生駒市図書館に無い場合はアイコン非表示

**Comment by hiroaki-ohkawa** [comment]
「生駒市のいずれかの図書館ですぐ借りれる」ということを知りたいユーザーもいると思う。
これを伝える良い方法も検討したい。

**Comment by nozutaku** [comment]
詳細画面は大川さん作のカーリル呼び出しAPIになりましたが、
全図書館情報を表示するようにしてますが、そのような仕様で進行します？
当初は自分が選択した図書館しか表示しない想定でしたが。

**Comment by nozutaku** [comment]
詳細画面で「これよも！予約する」ボタン押下でbooklist[].CityLibRentalURL へ遷移するのが未実装です。

**Comment by hiroaki-ohkawa** [comment]
2つ前のコメントに対して。次の打ち合わせでみんなと相談しましょう。

**Comment by nozutaku** [comment]
> 2つ前のコメントに対して。次の打ち合わせでみんなと相談しましょう。

了解！　agendaに記載しました。

**Comment by nozutaku** [comment]
＜仕様＞　11/3で決まった内容。MAに向けて対応予定。

-  一覧画面　→図書館アイコン無。並びはデフォルトでは自分の最寄りの図書館で借りれるか否かを考慮してソートする
- 詳細画面　→全ての本のある図書館を表示する（最寄り図書館以外も表示）。レンタル中はグレーアウト表示。

**Comment by nozutaku** [comment]
対応完了していますのでcloseします。
