### ISSUE TITLE
初期設定画面

### ISSUE THREAD

**Issue by nozutaku** [hiroaki-ohkawa/ikoma-library-app-proto#8]
下記２つを設定する初期設定画面
- 図書館選択
- 年齢層

**Comment by acliss19xx** [comment]
ea73c1bd23de2e04d52b184909841746093958a7
048767b3a3e24a2a6086d21ad2f1b582a351b524

**Comment by hiroaki-ohkawa** [comment]
以下、残タスク。
・初期設定画面で選んだ項目と、設定画面で選べる内容をリンクさせる
・設定内容を検索に反映させる

**Comment by nozutaku** [comment]
> 設定内容を検索に反映させる

念のための補足です。

年齢と最寄り図書館は下記を指定してget_list()を呼ぶと反映されます。（絵本だけでなく、児童書、児童文庫の選本評価を早くする必要性があるので早めに対応して欲しいです。。。）


- Setting.age

- Settig.libplace

https://github.com/hiroaki-ohkawa/ikoma-library-app-proto/blob/integrate-recommendation-2/routes/api/recommendation/get_list.js#L91

**Comment by nozutaku** [comment]
年齢選択時の不具合修正　commit 5f21c6f8880b5c2b781db6836c6dc394a4d49d3a

**Comment by nozutaku** [comment]
対応完了していますのでcloseします。
