### ISSUE TITLE
検索設定UI

### ISSUE THREAD

**Issue by nozutaku** [hiroaki-ohkawa/ikoma-library-app-proto#9]

**Comment by nozutaku** [comment]
固定ジャンルボタン表示も必要。

**Comment by hiroaki-ohkawa** [comment]
本イシューでやることは何でしょうか？

**Comment by nozutaku** [comment]
＜本issueでやること＞
- 「なによも?」ボタン押下時に表示する画面(9/22のFBメッセンジャーやりとりで決まったと理解）

- 現在、設定歯車ボタン押下→検索条件ボタン　押下時に表示している画面UIを「なによも」ボタン押下時へ引っ越し。主な内容は下記。

　・おすすめOn/Offを無にする

　・ #11 固定ジャンルでの検索ボタン　→固定ジャンルのみ（でした？）の本を表示（＋図書館有無や司書コメント有）

　・ 全ユーザー履歴の動的ジャンルボタン（機械学習など）　←内容が大きいので本issueで扱わない

　・ キーワード入力しての本検索（現状のような書名、著者名、出版社名を入れる形式にするか１つにするかは未決定）

- 上記UIにてユーザー入力後、決定ボタン押下で本一覧画面を表示

野田さんが画面デザイン予定

**Comment by nozutaku** [comment]
対応完了済。
